# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian/jessie64"
  config.vm.hostname = "qipr-approver"
  config.vm.synced_folder "../qipr_approver", "/var/www/qipr_approver"
  config.vm.network "private_network", ip: "192.168.222.3"
  config.vm.define "qipr_approver"

  config.vm.provision "shell" do |s|
    s.path = "bootstrap.sh"
  end

  # Restart apache when all done (if using apache)
  config.vm.provision "shell", run: "always", inline: "service apache2 restart"

  config.trigger.after [:up] do
    if Vagrant::Util::Platform.darwin?
      system("open -a 'Google Chrome.app' http://192.168.222.3")
    end
  end

end
