from approver.views.aboutyou import about_you
from approver.views.index import index
from approver.views.dashboard import dashboard
from approver.views.fake_shib import fake_shib
from approver.views.first_login import first_login
from approver.views.project import project
from approver.views.project_status import project_status
from approver.views.approve import approve
from approver.views.similar_projects import similar_projects
from approver.views.error404 import error404
from approver.views.userlist import userlist
from approver.views.aboutyou import about_you_superuser
