# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-05 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('gatorlink', models.CharField(max_length=50, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('url', models.TextField()),
                ('previous_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_log', to='approver.AccessLog')),
            ],
        ),
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ua_string', models.TextField()),
                ('ua_hash', models.CharField(editable=False, max_length=32)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='useragent',
            unique_together=set([('id', 'ua_hash')]),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='user_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='approver.UserAgent'),
        ),
    ]
