# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='guid_changed',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
