# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='objective',
            new_name='overall_goal',
        ),
        migrations.RemoveField(
            model_name='project',
            name='milestones',
        ),
        migrations.RemoveField(
            model_name='project',
            name='scope',
        ),
    ]
