# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approver', '0002_auto_20160728_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='training',
            name='description',
        ),
        migrations.AddField(
            model_name='address',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_address', to='approver.Organization'),
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buisness_address', to='approver.Person'),
        ),
        migrations.AddField(
            model_name='response',
            name='description',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
