# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approver', '0002_auto_20160927_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptor',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesh_keyword', to='approver.Project'),
        ),
    ]
