# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approver', '0002_accesslog_guid_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
