# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-05 19:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('approver', '0002_auto_20170105_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesslog',
            old_name='datetime',
            new_name='time_requested',
        ),
        migrations.AddField(
            model_name='accesslog',
            name='http_verb',
            field=models.CharField(default='BLARGH', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesslog',
            name='request_body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='response_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='time_responded',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 5, 19, 20, 13, 106528, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
