# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approver', '0003_auto_20160729_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
