# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 15:44
from __future__ import unicode_literals

import approver.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approver', '0003_auto_20170124_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(default=approver.utils.get_guid, editable=False, max_length=32)),
                ('in_registry', models.BooleanField(default=False)),
                ('business_email', models.CharField(max_length=100, null=True)),
                ('business_fax', models.CharField(max_length=20, null=True)),
                ('business_phone', models.CharField(max_length=50, null=True)),
                ('display_name', models.CharField(max_length=70)),
                ('first_name', models.CharField(max_length=30)),
                ('gatorlink', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('name_prefix', models.CharField(max_length=30)),
                ('name_suffix', models.CharField(max_length=30)),
                ('working_title', models.CharField(max_length=30)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='approver.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
