# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approver', '0003_auto_20160731_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_address', to='approver.Person'),
        ),
    ]
