# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approver', '0003_descriptor_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meshtreenumber',
            name='descriptor',
        ),
        migrations.AddField(
            model_name='descriptor',
            name='mesh_tree_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptor', to='approver.MeshTreeNumber'),
        ),
    ]
