# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approver', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=32)),
                ('model_name', models.CharField(max_length=20)),
            ],
        ),
    ]
