# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approver', '0004_contact'),
        ('approver', '0004_project_sent_email_list'),
    ]

    operations = [
    ]
