# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approver', '0005_merge_20170201_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='vivo_uri',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clinicalarea',
            name='vivo_uri',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clinicaldepartment',
            name='vivo_uri',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clinicalsetting',
            name='vivo_uri',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expertise',
            name='vivo_uri',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='focusarea',
            name='vivo_uri',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='vivo_uri',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='vivo_uri',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qi_interest',
            name='vivo_uri',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='vivo_uri',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suffix',
            name='vivo_uri',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clinicaldepartment',
            name='name',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
