# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approver', '0006_auto_20170222_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertise',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='last_modified_by',
        ),
        migrations.AlterField(
            model_name='person',
            name='expertise',
            field=models.ManyToManyField(to='approver.Descriptor'),
        ),
        migrations.DeleteModel(
            name='Expertise',
        ),
    ]
