# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approver', '0007_auto_20170209_1627'),
        ('approver', '0006_auto_20170209_1421'),
    ]

    operations = [
    ]
