# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approver', '0007_auto_20170227_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reached_irb_page_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_irb_page_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_needs_advisor_page_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reached_needs_advisor_page_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='expertise',
            field=models.ManyToManyField(related_name='persons', to='approver.Descriptor'),
        ),
    ]
